# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'script.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 471, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(30, 10, 76, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 10, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 10, 61, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 10, 76, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_5.setGeometry(QtCore.QRect(360, 10, 61, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_6.setGeometry(QtCore.QRect(310, 10, 51, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(428, 4, 41, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 40, 471, 551))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_7.setGeometry(QtCore.QRect(150, 10, 111, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 5, 41, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 40, 471, 551))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab)
        self.comboBox_8.setGeometry(QtCore.QRect(164, 10, 91, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(264, 5, 41, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "시작일"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "종료일"))
        self.comboBox.setItemText(0, _translate("MainWindow", "2014"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2015"))
        self.comboBox.setItemText(2, _translate("MainWindow", "2016"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_3.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_3.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_3.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_3.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_3.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_3.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_3.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_3.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_3.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_3.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_3.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_3.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_3.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_3.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_3.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_3.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_3.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_3.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "2014"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2015"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "2016"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "12"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "13"))
        self.comboBox_5.setItemText(13, _translate("MainWindow", "14"))
        self.comboBox_5.setItemText(14, _translate("MainWindow", "15"))
        self.comboBox_5.setItemText(15, _translate("MainWindow", "16"))
        self.comboBox_5.setItemText(16, _translate("MainWindow", "17"))
        self.comboBox_5.setItemText(17, _translate("MainWindow", "18"))
        self.comboBox_5.setItemText(18, _translate("MainWindow", "19"))
        self.comboBox_5.setItemText(19, _translate("MainWindow", "20"))
        self.comboBox_5.setItemText(20, _translate("MainWindow", "21"))
        self.comboBox_5.setItemText(21, _translate("MainWindow", "22"))
        self.comboBox_5.setItemText(22, _translate("MainWindow", "23"))
        self.comboBox_5.setItemText(23, _translate("MainWindow", "24"))
        self.comboBox_5.setItemText(24, _translate("MainWindow", "25"))
        self.comboBox_5.setItemText(25, _translate("MainWindow", "26"))
        self.comboBox_5.setItemText(26, _translate("MainWindow", "27"))
        self.comboBox_5.setItemText(27, _translate("MainWindow", "28"))
        self.comboBox_5.setItemText(28, _translate("MainWindow", "29"))
        self.comboBox_5.setItemText(29, _translate("MainWindow", "30"))
        self.comboBox_5.setItemText(30, _translate("MainWindow", "31"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "11"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "12"))
        self.pushButton.setText(_translate("MainWindow", "검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "기간별"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "지역"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "시작일"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "종료일"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "서울"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "인천"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "경기"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "충북"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "충남"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "경북"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "경남"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "대구"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "부산"))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "전북"))
        self.comboBox_7.setItemText(10, _translate("MainWindow", "전남"))
        self.comboBox_7.setItemText(11, _translate("MainWindow", "광주"))
        self.comboBox_7.setItemText(12, _translate("MainWindow", "대전"))
        self.comboBox_7.setItemText(13, _translate("MainWindow", "울산"))
        self.comboBox_7.setItemText(14, _translate("MainWindow", "제주"))
        self.pushButton_2.setText(_translate("MainWindow", "검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "지역별"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "시작일"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "종료일"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "연극/뮤지컬"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "국악"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "무용/발레"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "전시/박물관"))
        self.pushButton_3.setText(_translate("MainWindow", "검색"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "분류별"))

